/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        theme: {
          bg: 'var(--app-bg)',
          card: 'var(--app-card)',
          surface: 'var(--app-surface)',
          text: 'var(--app-text)',
          muted: 'var(--app-text-muted)',
          border: 'var(--app-border)',
        },
        gold: {
          50: '#FAF6ED',
          100: '#F5ECD6',
          200: '#ECD6A5',
          300: '#DFC074',
          400: '#D4AF37',
          500: '#C59B4E',
          600: '#B38738',
          700: '#9A7228',
          800: '#7B5716',
          900: '#523A0B',
          950: '#2E2005',
          obsidian: '#0D0A07',
          onyx: '#140F0A',
          shimmer: '#E8C97E',
        },
        royal: {
          dark: '#0D0A07',
          card: '#140F0A',
          cardHover: '#1A130C',
          gold: '#B38738',
          goldLight: '#E8C97E',
          goldDark: '#8F661E',
          border: 'rgba(179, 135, 56, 0.3)',
          borderGlow: 'rgba(212, 175, 55, 0.4)',
          parchment: '#FAF6ED',
        },
        brand: {
          orange: '#FF1F02',
          gold: '#B38738',
          goldDark: '#8F661E',
          ivory: '#FAF6ED',
          dark: '#0D0A07',
          black: '#000000',
          heading: '#0E0E0E',
          stroke: '#E9E9DE',
          strokeDark: '#333333',
          paragraph: '#D0D0D0',
          paragraph2: '#B0B0B0',
        },
        luxury: {
          dark: '#0D0A07',
          black: '#000000',
          stone: '#140F0A',
          muted: '#B0B0B0',
          light: '#FAF6ED',
          accent: '#B38738',
          gold: '#C59B4E',
          goldDark: '#8F661E',
          border: '#3A2C17',
        }
      },
      fontFamily: {
        royal: ['Marcellus', 'Cinzel', 'Playfair Display', 'serif'],
        marcellus: ['Marcellus', 'Cinzel', 'serif'],
        cinzel: ['Cinzel', 'serif'],
        cormorant: ['"Cormorant Garamond"', 'Playfair Display', 'Georgia', 'serif'],
        serif: ['"Cormorant Garamond"', 'Playfair Display', 'Georgia', 'serif'],
        italiana: ['Italiana', 'Cinzel', 'serif'],
        playfair: ['"Playfair Display"', 'Georgia', 'serif'],
        sans: ['"Plus Jakarta Sans"', 'Manrope', 'sans-serif'],
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
        manrope: ['Manrope', '"Plus Jakarta Sans"', 'sans-serif'],
        display: ['Marcellus', 'Cinzel', '"Cormorant Garamond"', 'serif'],
        momo: ['Marcellus', 'Cinzel', '"Cormorant Garamond"', 'serif'],
      },
    },
  },
  plugins: [],
}
