export const OFFERS_DATA = [
  {
    id: 'pkg-1',
    title: 'Royal Destination Wedding Package',
    tag: 'Celebration Special',
    category: 'Weddings',
    discount: 'Complimentary Decor Consultation',
    validTill: 'Valid Year-Round 2026',
    badge: 'MOST POPULAR',
    description: 'Complete 3-day wedding celebration package including pillarless banquet hall, oceanfront mandap setup, customized multi-cuisine royal buffet, bridal suite, and dedicated event coordinator.',
    inclusions: [
      'Pillarless Banquet & Manicured Lawn access',
      'Grand Multi-Cuisine Royal Banquet Spread',
      'Complimentary Suite for Bride & Groom',
      'Dedicated Event Planner & Hospitality Desk',
      'Pre-Wedding Photoshoot Venue Access'
    ],
    location: 'Chennai & Mumbai Properties',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=90',
    featured: true,
  },
  {
    id: 'pkg-3',
    title: 'Executive Corporate Offsite & Summit',
    tag: 'Corporate & Boardrooms',
    category: 'Corporate',
    discount: 'Group Privilege Rates',
    validTill: 'Weekday Booking Advantage',
    badge: 'CORPORATE HUB',
    description: 'High-tech conference rooms, audio-visual stage setups, executive banqueting, and team-building recreational pool activities for seamless corporate leadership summits.',
    inclusions: [
      'Smart High-Tech Boardrooms & Stage',
      'Morning & Evening High-Tea with Hors d\'oeuvres',
      'Customized Executive Lunch Buffets',
      'Team-Building Recreation Lawn Access',
      '24/7 Dedicated Business Concierge'
    ],
    location: 'Noida & Delhi Capital Hubs',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=90',
    featured: true,
  },
  {
    id: 'pkg-4',
    title: 'Early Bird Holiday Family Getaway',
    tag: 'Family Holiday Escape',
    category: 'Holidays',
    discount: 'Complimentary Kids Dining & Activities',
    validTill: 'Book 15 Days in Advance',
    badge: 'EARLY BIRD',
    description: 'Craft joyful family memories with spacious interconnecting luxury suites, complimentary gourmet breakfast, dedicated kids play zones, and guided local city tours.',
    inclusions: [
      'Complimentary Stay & Dine for Kids under 10',
      'Lavish Daily Buffet Breakfast',
      'Free Access to Kids Game Arcade & Pool',
      'Guided Local Sightseeing Itinerary',
      'Welcome Drinks & Fruit Basket on Arrival'
    ],
    location: 'Chennai & Mumbai Coastal Gateways',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=90',
    featured: true,
  },
  {
    id: 'pkg-5',
    title: 'Romantic Candlelight Anniversary Escape',
    tag: 'Couples & Romance',
    category: 'Romance',
    discount: 'Private Candlelit Dinner Included',
    validTill: 'Valid Throughout 2026',
    badge: 'ROMANCE RETREAT',
    description: 'Celebrate your special milestone with a private candlelight poolside dinner, personalized floral room decor, champagne bottle, and serene sunset balcony views.',
    inclusions: [
      'Floral Decorated Signature Suite',
      '4-Course Private Candlelight Chef Tasting',
      'Complimentary Cake & Sparkling Wine',
      'In-Room Breakfast in Bed',
      'Sunset High-Tea on Balcony'
    ],
    location: 'All Properties',
    image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=90',
    featured: false,
  },
  {
    id: 'pkg-6',
    title: 'Grand Birthday & Anniversary Gala Package',
    tag: 'Banquets & Celebrations',
    category: 'Celebrations',
    discount: 'Custom Theme Setup Support',
    validTill: 'Book Anytime with Event Desk',
    badge: 'EVENT SPECIAL',
    description: 'Host memorable birthday bashes and milestone parties with tailor-made stage decor, live DJ/acoustic music support, mocktail bar, and extensive multi-cuisine spread.',
    inclusions: [
      'Indoor AC Banquet or Poolside Deck Setup',
      'Themed Floral & Lighting Decor',
      'Multi-Cuisine Gourmet Feast Menu',
      'Sound & Music Setup Support',
      'Dedicated Hospitality Manager'
    ],
    location: 'Chennai, Noida, Mumbai & Delhi',
    image: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=1200&q=90',
    featured: false,
  }
];
