export const ROUTES = {
  HOME: '/',
  RESORTS: '/resorts',
  RESORT_DETAILS: '/resorts/:slug',
  HOTELS: '/hotels',
  HOTEL_DETAILS: '/hotels/:slug',
  EXPERIENCES: '/experiences',
  SANCTUARY_RITUALS: '/sanctuary-rituals',
  SANCTUARY_ETHOS: '/sanctuary-ethos',
  ETHOS: '/ethos',
  GALLERY: '/gallery',
  OFFERS: '/offers',
  PACKAGES: '/packages',
  ABOUT: '/about',
  CONTACT: '/contact',
  CELEBRATIONS: '/celebrations',
  EVENTS: '/events',
  PRIVACY: '/privacy-policy',
  TERMS: '/terms',
  LOGIN: '/login',
  ADMIN_LOGIN: '/admin/login',
  ADMIN: '/admin',
};
