export const EXPERIENCES_DATA = [
  {
    id: 'exp-1',
    title: 'Sunset Yacht Charter & Coastal Safari',
    category: 'Ocean & Water',
    location: 'Goa Coast',
    duration: 'Half Day',
    description: 'Private catamaran charter exploring secluded coves with artisan champagne tasting and dolphin pods at golden hour.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    id: 'exp-2',
    title: 'Himalayan Heli-Skiing & Ridge Picnic',
    category: 'Adventure',
    location: 'Manali Glaciers',
    duration: 'Full Day',
    description: 'Fly by chartered helicopter to untouched mountain powder accompanied by private mountain guides and chef-prepared hot lunch.',
    image: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    id: 'exp-3',
    title: 'Ancient Ayurvedic Thermal Bath & Sound Therapy',
    category: 'Spa & Wellness',
    location: 'All Properties',
    duration: '3 Hours',
    description: 'Custom botanical oil infusions, steam hammam, and Tibetan singing bowl resonance tailored to cellular rejuvenation.',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    id: 'exp-4',
    title: 'Desert Dune Candlelit Astronomy Dinner',
    category: 'Culinary & Heritage',
    location: 'Jaipur Desert',
    duration: 'Evening',
    description: 'An intimate desert supper crafted over open embers with celestial stargazing through high-powered observatory telescopes.',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80',
    featured: true,
  },
  {
    id: 'exp-5',
    title: 'Master Sommelier Cellar Degustation',
    category: 'Fine Dining',
    location: 'Mumbai Tower',
    duration: '2.5 Hours',
    description: 'Exclusive access to our subterranean collection of rare vintages paired with bespoke six-course culinary creations.',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80',
    featured: false,
  },
  {
    id: 'exp-6',
    title: 'Botanical Foraging & Farm-to-Glass Workshop',
    category: 'Nature',
    location: 'Bengaluru Garden',
    duration: 'Morning',
    description: 'Harvest rare aromatic flora alongside our master herbalist, crafting bespoke elixirs and botanical tinctures.',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
    featured: false,
  },
];
