export const GALLERY_DATA = [
  {
    id: 'gal-1',
    category: 'Resorts',
    title: 'Azure Coast Sea Pavilion',
    location: 'Goa, India',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1400&q=80',
    aspect: 'aspect-cinematic',
  },
  {
    id: 'gal-2',
    category: 'Resorts',
    title: 'Serena Glacial Horizon',
    location: 'Manali, Himalayas',
    image: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1200&q=80',
    aspect: 'aspect-editorial',
  },
  {
    id: 'gal-3',
    category: 'Hotels',
    title: 'Grand Vista Rooftop Infinity Pool',
    location: 'Mumbai Skyline',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=80',
    aspect: 'aspect-cinematic',
  },
  {
    id: 'gal-4',
    category: 'Rooms',
    title: 'Cliffside Master Soaking Suite',
    location: 'Azure Coast',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    aspect: 'aspect-editorial',
  },
  {
    id: 'gal-5',
    category: 'Dining',
    title: 'Sandstone Courtyard Degustation',
    location: 'Jaipur Palace',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=80',
    aspect: 'aspect-cinematic',
  },
  {
    id: 'gal-6',
    category: 'Experiences',
    title: 'Vedic Thermal Spa Pavilion',
    location: 'Botanical Sanctuary',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1200&q=80',
    aspect: 'aspect-editorial',
  },
  {
    id: 'gal-7',
    category: 'Nature',
    title: 'Alpine Morning Mist',
    location: 'Himalayan Ridge',
    image: 'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1400&q=80',
    aspect: 'aspect-cinematic',
  },
  {
    id: 'gal-8',
    category: 'Hotels',
    title: 'Vertical Botanical Architecture',
    location: 'Bengaluru Retreat',
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
    aspect: 'aspect-editorial',
  },
];
