export const RESORTS_DATA = [
  {
    id: 'resort-1',
    name: 'Azure Coast Sanctuary',
    slug: 'azure-coast-resort',
    tagline: 'Oceanfront Brutalism & Coastal Serenity',
    location: 'Goa, India',
    city: 'Goa',
    state: 'Goa',
    country: 'India',
    region: 'Coastal West',
    heroImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1920&q=80',
    featuredImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Perched over secluded cliffs overlooking the Arabian Sea, blending raw monolithic architecture with verdant coastal rainforests.',
    description: 'Azure Coast Sanctuary is a triumph of contemporary architectural minimalism set against the raw power of the ocean. Each private pavilion is framed by cascading cantilevered terraces, offering uninterrupted ocean vistas, private infinity dip pools, and bespoke open-air living spaces designed for profound solitude.',
    rating: 4.98,
    featured: true,
    status: 'active',
    contact: {
      phone: '+91 98765 43210',
      whatsapp: '+919876543210',
      email: 'azurecoast@aura-resorts.com',
      address: 'Cliff Edge Drive, Morjim Coast, Goa 403512, India',
    },
    amenities: [
      { name: 'Private Cliff Infinity Pool', icon: 'Waves' },
      { name: 'Ayurvedic Thermal Spa', icon: 'Sparkles' },
      { name: 'Seafood Pavilion & Cellar', icon: 'Utensils' },
      { name: 'Helipad & Chauffeur Fleet', icon: 'Compass' },
      { name: 'High-Speed Mesh WiFi', icon: 'Wifi' },
      { name: '24-Hour Private Butler', icon: 'ShieldCheck' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    ],
    rooms: [
      {
        id: 'r1-room1',
        name: 'The Oceanfront Cantilever Villa',
        size: '2,800 sq ft',
        capacity: 'Up to 3 Guests',
        bedType: 'Custom King Bed',
        view: '180° Panoramic Arabian Sea',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80',
        description: 'Suspended above the coastal rocks with floor-to-ceiling glass, outdoor brass soaking tub, and basalt sun terrace.',
        amenities: ['Private Plunge Pool', 'Outdoor Rain Shower', 'Sub-Zero Wine Cellar', 'Sonos Sound System'],
      },
      {
        id: 'r1-room2',
        name: 'The Cliffside Pavilion',
        size: '1,950 sq ft',
        capacity: '2 Guests',
        bedType: 'Emperor Silk Bed',
        view: 'Direct Ocean & Tropical Garden',
        image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=80',
        description: 'Immersed in native flora with an open courtyard, custom stone masonry, and sunset contemplation deck.',
        amenities: ['Private Garden Garden', 'Deep Soaking Tub', 'Espresso Bar', 'Dyson Amenities'],
      },
    ],
    experiences: [
      {
        id: 'r1-exp1',
        title: 'Sunset Yacht Charter & Marine Safari',
        category: 'Ocean Experience',
        description: 'Private catamaran excursion along the emerald coastline with champagne pairings at golden hour.',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'r1-exp2',
        title: 'Vedic Sound Healing & Herbal Therapies',
        category: 'Wellness',
        description: 'Ancient Ayurvedic therapies crafted around personal doshas inside cliffside open-air pavilions.',
        image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=800&q=80',
      },
    ],
  },
  {
    id: 'resort-2',
    name: 'Serena Alpine Sanctuary',
    slug: 'serena-alpine-sanctuary',
    tagline: 'High Altitude Cedar Retreat',
    location: 'Manali, Himachal Pradesh',
    city: 'Manali',
    state: 'Himachal Pradesh',
    country: 'India',
    region: 'Northern Himalayas',
    heroImage: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1920&q=80',
    featuredImage: 'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Nestled amidst ancient deodar forests and snow-crowned Himalayan peaks, sculpted from slate, timber, and glass.',
    description: 'Serena Alpine Sanctuary redefines mountain luxury. Designed to harmonize with dramatic alpine contours, each timber-clad suite features heated stone flooring, handcrafted fireplaces, and private glass conservatories facing perpetual glaciers.',
    rating: 4.96,
    featured: true,
    status: 'active',
    contact: {
      phone: '+91 98765 43211',
      whatsapp: '+919876543211',
      email: 'serena@aura-resorts.com',
      address: 'Old Forest Ridge, Upper Solang Valley, Manali 175131, India',
    },
    amenities: [
      { name: 'Heated Geothermal Infinity Pool', icon: 'Waves' },
      { name: 'Alpine Cedarwood Sauna', icon: 'Sparkles' },
      { name: 'Artisan Himalayan Foraging Table', icon: 'Utensils' },
      { name: 'Ski Concierge & Trail Guides', icon: 'Compass' },
      { name: 'Stargazing Observatory Dome', icon: 'Eye' },
      { name: '24-Hour Fireplace Attendant', icon: 'ShieldCheck' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    ],
    rooms: [
      {
        id: 'r2-room1',
        name: 'The Glacial Vista Chalet',
        size: '3,200 sq ft',
        capacity: 'Up to 4 Guests',
        bedType: 'Double King Suites',
        view: 'Unobstructed Himalayan Snowpeaks',
        image: 'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1000&q=80',
        description: 'Multi-level chalet with wood-burning stone hearth, private cedar hot tub, and panoramic glass conservatory.',
        amenities: ['Cedar Hot Tub', 'Underfloor Heating', 'Private Bar', 'Mountain View Balcony'],
      },
    ],
    experiences: [
      {
        id: 'r2-exp1',
        title: 'Glacial Heli-Skiing & Ridge Picnics',
        category: 'Alpine Adventure',
        description: 'Chartered helicopter transport to virgin powder ridges accompanied by professional alpine guides.',
        image: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=800&q=80',
      },
    ],
  },
  {
    id: 'resort-3',
    name: 'Oasis Mirage Palace',
    slug: 'oasis-mirage-palace',
    tagline: 'Royal Heritage & Desert Architecture',
    location: 'Jaipur, Rajasthan',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    region: 'North West Desert',
    heroImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1920&q=80',
    featuredImage: 'https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'A modern architectural ode to Rajputana grandeur, surrounded by dunes, geometric water courts, and sandstone arches.',
    description: 'Rising like a majestic mirage in the Golden Triangle, Oasis Mirage combines traditional lime-plaster craftsmanship with bold modernist proportions, tranquil reflection pools, and desert night skies.',
    rating: 4.99,
    featured: true,
    status: 'active',
    contact: {
      phone: '+91 98765 43212',
      whatsapp: '+919876543212',
      email: 'mirage@aura-resorts.com',
      address: 'Amer Foothills, Amber Ring, Jaipur 302028, India',
    },
    amenities: [
      { name: 'Marble Courtyard Step-Pool', icon: 'Waves' },
      { name: 'Royal Scent & Hammam Suite', icon: 'Sparkles' },
      { name: 'Heritage Degustation Dining', icon: 'Utensils' },
      { name: 'Private Dune Buggies & Camels', icon: 'Compass' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=1200&q=80',
    ],
    rooms: [
      {
        id: 'r3-room1',
        name: 'The Maharaja Sandstone Suite',
        size: '2,600 sq ft',
        capacity: '2 Guests',
        bedType: 'Palace Canopy Bed',
        view: 'Inner Reflection Pool & Aravalli Hills',
        image: 'https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=1000&q=80',
        description: 'Featuring intricate carved jali screens, private courtyard plunge bath, and royal heritage antiques.',
        amenities: ['Marble Plunge Pool', 'Private Courtyard', 'Bespoke Perfumery Bar', '24h Attendant'],
      },
    ],
    experiences: [
      {
        id: 'r3-exp1',
        title: 'Desert Dunes Stargazing & Candlelit Feast',
        category: 'Heritage Experience',
        description: 'Private tented dining on undulating desert dunes with traditional sitar and astronomy guides.',
        image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
      },
    ],
  },
];
