export const ALL_ROOMS = [
  {
    id: 'room-1',
    propertyId: 'resort-1',
    propertyName: 'Azure Coast Sanctuary',
    propertyType: 'Resort',
    slug: 'oceanfront-cantilever-villa',
    name: 'The Oceanfront Cantilever Villa',
    size: '2,800 sq ft',
    capacity: 'Up to 3 Guests',
    bedType: 'Custom King Bed',
    view: 'Panoramic Arabian Sea',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    description: 'Suspended above coastal basalt rocks with floor-to-ceiling glass, outdoor brass soaking tub, and sunset contemplation deck.',
    amenities: ['Private Infinity Plunge Pool', 'Outdoor Rain Shower', 'Sub-Zero Wine Cellar', 'Sonos Acoustic Hub', '24h Private Butler'],
    featured: true,
  },
  {
    id: 'room-2',
    propertyId: 'resort-2',
    propertyName: 'Serena Alpine Sanctuary',
    propertyType: 'Resort',
    slug: 'glacial-vista-chalet',
    name: 'The Glacial Vista Chalet',
    size: '3,200 sq ft',
    capacity: 'Up to 4 Guests',
    bedType: 'Dual King Suites',
    view: 'Himalayan Glacial Peaks',
    image: 'https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80',
    description: 'Multi-level chalet with wood-burning stone hearth, private cedar hot tub, and panoramic glass conservatory facing perpetual snowpeaks.',
    amenities: ['Cedar Hot Tub', 'Underfloor Heating', 'Private Hearth', 'Mountain Balcony', 'Ski Concierge'],
    featured: true,
  },
  {
    id: 'room-3',
    propertyId: 'hotel-1',
    propertyName: 'The Grand Vista Urban Tower',
    propertyType: 'Hotel',
    slug: 'skyline-presidential-penthouse',
    name: 'The Skyline Presidential Penthouse',
    size: '3,500 sq ft',
    capacity: '4 Guests',
    bedType: 'Dual King Master Suites',
    view: '360° Arabian Sea & Skyline',
    image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80',
    description: 'Private high-speed elevator access, marble fireplace, private tasting lounge, and wraparound sunset terrace.',
    amenities: ['Sky Terrace', 'Marble Steam Shower', 'Private Sommelier Service', 'Acoustic Soundproofing'],
    featured: true,
  },
  {
    id: 'room-4',
    propertyId: 'resort-3',
    propertyName: 'Oasis Mirage Palace',
    propertyType: 'Resort',
    slug: 'maharaja-sandstone-suite',
    name: 'The Maharaja Sandstone Suite',
    size: '2,600 sq ft',
    capacity: '2 Guests',
    bedType: 'Palace Canopy Bed',
    view: 'Inner Reflection Pool & Dunes',
    image: 'https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=1200&q=80',
    description: 'Carved jali screens, marble soaking pool, and private courtyard reflection pavilion.',
    amenities: ['Private Courtyard', 'Step Plunge Bath', 'Bespoke Attendant', 'Royal Heritage Interiors'],
    featured: false,
  },
];
