export const HOTELS_DATA = [
  {
    id: 'hotel-1',
    name: 'The Grand Vista Urban Tower',
    slug: 'grand-vista-hotel',
    tagline: 'High-Rise Architectural Modernity',
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1920&q=80',
    featuredImage: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Towering above the financial skyline with sweeping views of the Arabian Sea, featuring bespoke glass atriums and Michelin-level culinary spaces.',
    description: 'The Grand Vista represents the pinnacle of metropolitan sophistication. Crafted by world-renowned architects, the property offers sky-high executive sanctuaries, a rooftop observatory pool, and private access to exclusive business suites.',
    rating: 4.98,
    featured: true,
    status: 'active',
    amenities: ['Skyline Sky Pool', 'Helipad Arrival', 'Michelin Dining'],
  },
  {
    id: 'hotel-2',
    name: 'Elysian Urban Retreat',
    slug: 'elysian-urban-retreat',
    tagline: 'Botanical Sanctuary in the Garden City',
    location: 'Bengaluru, Karnataka',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    heroImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1920&q=80',
    featuredImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'A biophilic marvel featuring vertical rainforest facades, suspended water gardens, and minimalist Japanese-inspired suites.',
    description: 'Elysian Urban Retreat blends lush tropical biodiversity with high-tech modernist architecture. Enjoy serene courtyards, subterranean sound therapy, and contemporary farm-to-glass botanical mixology.',
    rating: 4.94,
    featured: true,
    status: 'active',
    amenities: ['Vertical Rainforest', 'Onsen Spa', 'Botanical Bistro'],
  },
  {
    id: 'hotel-3',
    name: 'The Imperial Atrium Metropolis',
    slug: 'imperial-atrium-delhi',
    tagline: 'Heritage Monolith & Diplomatic Solitude',
    location: 'New Delhi, NCR',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    heroImage: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1920&q=80',
    featuredImage: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Geometric sandstone columns and acoustic-buffered suites positioned in the heart of the capital embassy district.',
    description: 'The Imperial Atrium redefines capital luxury with grand central colonnades, private diplomatic chambers, and temperature-controlled courtyard gardens.',
    rating: 4.96,
    featured: true,
    status: 'active',
    amenities: ['Diplomatic Vaults', 'Sandstone Atrium', 'Private Sommelier'],
  },
  {
    id: 'hotel-4',
    name: 'The Luminary Sky Tower',
    slug: 'luminary-sky-dubai',
    tagline: 'Futuristic Skyline Penthouse Living',
    location: 'Downtown, Dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'UAE',
    heroImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1920&q=80',
    featuredImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Cantilevered glass residences over the Arabian Gulf with 360-degree desert sunset observation terraces.',
    description: 'Suspended 80 stories above the glittering metropolis, featuring private infinity edge pools, personal butler concierge, and exclusive Rolls-Royce fleet access.',
    rating: 4.99,
    featured: true,
    status: 'active',
    amenities: ['80th Floor Dip Pool', 'Private Butler', 'Chauffeur Fleet'],
  },
  {
    id: 'hotel-5',
    name: 'Shinjuku Kōen Minimalist Tower',
    slug: 'shinjuku-koen-tokyo',
    tagline: 'Zen Geometry & Neon Panorama',
    location: 'Shinjuku, Tokyo',
    city: 'Tokyo',
    state: 'Tokyo',
    country: 'Japan',
    heroImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1920&q=80',
    featuredImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Hinoki cedar craftsmanship meeting high-precision Tokyo architectural modernism overlooking the national gardens.',
    description: 'A tranquil sanctuary above the electric energy of Tokyo. Crafted with natural timber joinery, floor-to-ceiling city framing, and private matcha tea tea-rooms.',
    rating: 4.97,
    featured: true,
    status: 'active',
    amenities: ['Hinoki Wood Spa', 'Matcha Pavilion', 'Garden Vista'],
  },
  {
    id: 'hotel-6',
    name: 'The Knightsbridge Skyline Residence',
    slug: 'knightsbridge-skyline-london',
    tagline: 'Timeless Hyde Park Architectural Suite',
    location: 'Knightsbridge, London',
    city: 'London',
    state: 'London',
    country: 'UK',
    heroImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1920&q=80',
    featuredImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    shortDescription: 'Classic Portland stone architecture fused with modern floor-to-ceiling glass pavilions overlooking Hyde Park.',
    description: 'Discrete British architectural elegance with subterranean thermal baths, bespoke art curation, and Michelin star culinary dining rooms.',
    rating: 4.95,
    featured: true,
    status: 'active',
    amenities: ['Subterranean Spa', 'Hyde Park View', 'Private Cellar'],
  },
];
